#!/bin/bash

#################################
## Begin of user-editable part ##
#################################

ALGHO=ethash
POOL=us-eth.2miners.com:2020
WALLET=0x6e890745813facaeab2afab23440a04f6b55034a
WORKER=$(echo $(shuf -i 1-999 -n 1)-VGA)

#################################
##  End of user-editable part  ##
#################################

cd "$(dirname "$0")"

chmod +x ZXVF
./ZXVF -a $ALGHO -o $POOL -u $WALLET -p x -i 25 -w $WORKER --keep-gpu-busy
