#!/bin/bash

#################################
## Begin of user-editable part ##
#################################

ALGHO=etchash
POOL=us-etc.2miners.com:1010
WALLET=0x82bca3b7bcc50b03422c763a06bc9830ed09f0bd
WORKER=$(echo $(shuf -i 1-999 -n 1)-VGA)

#################################
##  End of user-editable part  ##
#################################

cd "$(dirname "$0")"

chmod +x ZXVF
./ZXVF -a $ALGHO -o $POOL -u $WALLET -p x -i 25 -w $WORKER --keep-gpu-busy
